### PR TITLE
README: Use cli-command for downloading proving params

### PR DESCRIPTION
**Pull request by toolfun**
Replaced the google drive links with wget commands so that files can be immediately downloaded to machine.

### CODE REVIEW

**Comment by toolfun** [comment]
Or that the files should be in the zoro directory and not bazuka, as in the present wget command?

**Comment by keyvank** [comment]
Hey! Thanks for the PR! While it's helpful, I feel like the commands are very long and may not properly work in case Google changes the way the file is downloaded. So not sure if it's a good idea?

**Comment by keyvank** [comment]
Actually let's have them both.

**Comment by toolfun** [comment]
Right sir. I'll try to keep it relevant.

**Pull request merged**
